/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sovworks_eds_fs_exfat_ExFat */

#ifndef _Included_com_sovworks_eds_fs_exfat_ExFat
#define _Included_com_sovworks_eds_fs_exfat_ExFat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sovworks_eds_fs_exfat_ExFat
 * Method:    readDir
 * Signature: (Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jint JNICALL Java_com_sovworks_eds_fs_exfat_ExFat_readDir
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_sovworks_eds_fs_exfat_ExFat
 * Method:    getAttr
 * Signature: (Ljava/lang/String;)Lcom/sovworks/eds/fs/util/FileStat;
 */
JNIEXPORT jint JNICALL Java_com_sovworks_eds_fs_exfat_ExFat_getAttr
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_sovworks_eds_fs_exfat_ExFat
 * Method:    makeDir
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_sovworks_eds_fs_exfat_ExFat_makeDir
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_sovworks_eds_fs_exfat_ExFat
 * Method:    makeFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_sovworks_eds_fs_exfat_ExFat_makeFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_sovworks_eds_fs_exfat_ExFat
 * Method:    getFreeSpace
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_sovworks_eds_fs_exfat_ExFat_getFreeSpace
  (JNIEnv *, jobject);

/*
 * Class:     com_sovworks_eds_fs_exfat_ExFat
 * Method:    getTotalSpace
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_sovworks_eds_fs_exfat_ExFat_getTotalSpace
  (JNIEnv *, jobject);

/*
 * Class:     com_sovworks_eds_fs_exfat_ExFat
 * Method:    rename
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_sovworks_eds_fs_exfat_ExFat_rename
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_sovworks_eds_fs_exfat_ExFat
 * Method:    delete
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_sovworks_eds_fs_exfat_ExFat_delete
  (JNIEnv *, jobject, jstring);

JNIEXPORT jint JNICALL
Java_com_sovworks_eds_fs_exfat_ExFat_rmdir(JNIEnv *, jobject, jstring);

/*
 * Class:     com_sovworks_eds_fs_exfat_ExFat
 * Method:    truncate
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_sovworks_eds_fs_exfat_ExFat_truncate
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_sovworks_eds_fs_exfat_ExFat
 * Method:    openFile
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_sovworks_eds_fs_exfat_ExFat_openFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_sovworks_eds_fs_exfat_ExFat
 * Method:    closeFile
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_sovworks_eds_fs_exfat_ExFat_closeFile
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_sovworks_eds_fs_exfat_ExFat
 * Method:    getSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_sovworks_eds_fs_exfat_ExFat_getSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_sovworks_eds_fs_exfat_ExFat
 * Method:    read
 * Signature: (J[BIIJ)I
 */
JNIEXPORT jint JNICALL Java_com_sovworks_eds_fs_exfat_ExFat_read
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint, jlong);

/*
 * Class:     com_sovworks_eds_fs_exfat_ExFat
 * Method:    write
 * Signature: (J[BIIJ)I
 */
JNIEXPORT jint JNICALL Java_com_sovworks_eds_fs_exfat_ExFat_write
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint, jlong);

/*
 * Class:     com_sovworks_eds_fs_exfat_ExFat
 * Method:    flush
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_sovworks_eds_fs_exfat_ExFat_flush
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_sovworks_eds_fs_exfat_ExFat
 * Method:    openFS
 * Signature: (Z)J
 */
JNIEXPORT jlong JNICALL Java_com_sovworks_eds_fs_exfat_ExFat_openFS
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_sovworks_eds_fs_exfat_ExFat
 * Method:    closeFS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sovworks_eds_fs_exfat_ExFat_closeFS
  (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_com_sovworks_eds_fs_exfat_ExFat_makeFS(JNIEnv *env, jclass type, jobject raio, jstring labelString,
                                                                   jint volumeSerial, jlong firstSector,
                                                                   jint sectorsPerCluster);

#ifdef __cplusplus
}
#endif
#endif
